services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: ${PUID}:${PGID}
    volumes:
        - ${CONFIG_PATH}:/opt/JDownloader/app/cfg
        - ${DOWNLOAD_PATH}:/opt/JDownloader/Downloads
        - /etc/localtime:/etc/localtime:ro
    ports:
        - 3129:3129
    env_file: .env