services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
