services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    labels:
      # GENERAL
      - "traefik.enable=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      # HTTPS
      - "traefik.http.routers.vaultwarden-https.rule=Host(`${VAULTWARDEN_HOST}`) || Host(`vaultwarden.rubinoinformatica.it`)"
      - "traefik.http.routers.vaultwarden-https.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-https.tls=true"
      - "traefik.http.routers.vaultwarden-https.tls.certresolver=production"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true