services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true