version: "3.4"

services:
  paperless_redis:
    image: docker.io/library/redis:latest
    container_name: paperless_redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - paperless_default

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - paperless_redis
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      # GENERAL
      - "traefik.enable=true"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      # HTTPS
      - "traefik.http.routers.paperless-https.rule=Host(`${PAPERLESS_HOST}`)"
      - "traefik.http.routers.paperless-https.entrypoints=websecure"
      - "traefik.http.routers.paperless-https.tls=true"
      - "traefik.http.routers.paperless-https.tls.certresolver=production"
      # WATCHTOWER
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${DATA_PATH}/paperless/data:/usr/src/paperless/data
      - ${DATA_PATH}/paperless/media:/usr/src/paperless/media
      - ${DATA_PATH}/paperless/export:/usr/src/paperless/export
      - ${DATA_PATH}/paperless/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless_redis:6379
    networks:
      - traefik_proxy
      - paperless_default

volumes:
  redisdata:
  media:
  data:

networks:
  traefik_proxy:
    external: true
  paperless:
    name: paperless_default
    internal: true
