version: "3.4"

services:
  paperless_redis:
    image: docker.io/library/redis:latest
    container_name: paperless_redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - paperless

  paperless_db:
    image: postgres:latest
    container_name: paperless_db
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - paperless
    env_file: .env

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - paperless_redis
      - paperless_db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${PAPERLESS_DATA_PATH}/data:/usr/src/paperless/data
      - ${PAPERLESS_DATA_PATH}/media:/usr/src/paperless/media
      - ${PAPERLESS_DATA_PATH}/export:/usr/src/paperless/export
      - ${PAPERLESS_DATA_PATH}/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless_redis:6379
      PAPERLESS_DBHOST: paperless_db
    networks:
      - traefik_proxy
      - paperless

volumes:
  redisdata:

networks:
  traefik_proxy:
    external: true
  paperless:
    name: paperless_default
    internal: true