version: "3.3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik/:ro
      - ./certificates:/certificates
    networks:
      - traefik_proxy
    extra_hosts: 
      - host.docker.internal:172.17.0.1

networks:
  traefik_proxy:
    external: true