services:
  nextcloud_db:
    image: postgres:16.4
    restart: unless-stopped
    container_name: nextcloud_db
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nextcloud

  app:
    image: nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    depends_on:
      - nextcloud_db
      - redis
    volumes:
      - ${NEXTCLOUD_CONFIG}:/var/www/html
      - ${NEXTCLOUD_DATA}:/var/www/html/data
    networks:
      - traefik_proxy
      - nextcloud

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: nextcloud_redis
    volumes:
      - redis:/data
    networks:
      - nextcloud

networks:
  traefik_proxy:
    external: true
  nextcloud:
    internal: true

volumes:
  redis:
  db:
