version: "2.1"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    env_file: .env
    network_mode: host
    labels:
      # GENERAL
      - "traefik.enable=true"
      - "traefik.http.services.hassio.loadbalancer.server.port=8123"
      # HTTPS
      - "traefik.http.routers.hassio-https.rule=Host(`${HASSIO_HOST}`)"
      - "traefik.http.routers.hassio-https.entrypoints=websecure"
      - "traefik.http.routers.hassio-https.tls=true"
      - "traefik.http.routers.hassio-https.tls.certresolver=production"
    volumes:
      - ${HASS_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    privileged: true

  hassio_db:
    image: postgres:latest
    restart: always
    container_name: hassio_db
    env_file: .env
    network_mode: host
    volumes:
      - ${HASS_CONFIG_PATH}/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    env_file: .env
    volumes:
    - ${MOSQUITTO_CONFIG_PATH}/config:/mosquitto/config
    - ${MOSQUITTO_CONFIG_PATH}/log:/mosquitto/log
    - ${MOSQUITTO_CONFIG_PATH}/data/:/mosquitto/data
    restart: always
    ports:
    - 1883:1883