version: "2.1"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ${CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    env_file: .env
