version: "2.1"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ${HASS_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    env_file: .env

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - ${MOSQUITTO_CONFIG_PATH}/config:/mosquitto/config
    - ${MOSQUITTO_CONFIG_PATH}/log:/mosquitto/log
    - ${MOSQUITTO_CONFIG_PATH}/data/:/mosquitto/data
    restart: always
    ports:
    - "1883:1883" 
