services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file: .env
    environment:
      - WATCHTOWER_CLEANUP=true
      - DOCKER_API_VERSION=1.41
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - TZ=Europe/Rome
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_BOT_TOKEN}@telegram?channels=${TELEGRAM_CHAT_ID}
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
