services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare
    restart: unless-stopped
    volumes:
      - ./config/config.json:/config.json:ro
    deploy:
      resources:
        limits:
          memory: 64m