version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${DATA_PATH}/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always