services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    volumes:
      - ${DATA_PATH}/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
